"""Unit tests for OrcaClient against a local mock HTTP server."""

import http.server
import json
import threading
import unittest
from typing import Any, Dict

from orcaslicer_matrix.client import OrcaApiError, OrcaAuthError, OrcaClient


MOCK_TOKEN = "test-token-12345"


class MockOrcaHandler(http.server.BaseHTTPRequestHandler):
    # Class-level mock state
    config_store: Dict[str, str] = {
        "layer_height": "0.2",
        "wall_loops": "2",
        "sparse_infill_density": "15%",
        "filament_cost": "25.0",
    }
    slice_attempts: int = 0
    fail_slice_once: bool = False

    def log_message(self, format, *args):
        # Silence console log spam during tests
        pass

    def _check_auth(self) -> bool:
        token = self.headers.get("X-Api-Token")
        if token != MOCK_TOKEN:
            self.send_response(401)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            self.wfile.write(json.dumps({"error": "unauthorized"}).encode("utf-8"))
            return False
        return True

    def do_GET(self):
        if not self._check_auth():
            return

        path = self.path.split("?")[0]
        if path == "/api/v1/status":
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            resp = {
                "app": "OrcaSlicer",
                "app_version": "2.4.2",
                "slice_result_valid": True,
                "presets": {
                    "print": "0.20mm Standard",
                    "printer": "Bambu Lab P1S 0.4 nozzle",
                    "filament": "Elegoo PETG Rapid",
                },
            }
            self.wfile.write(json.dumps(resp).encode("utf-8"))

        elif path == "/api/v1/objects":
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            resp = {
                "objects": [
                    {"id": 1, "name": "Benchy.stl"},
                    {"id": 2, "name": "CalibrationCube.stl"},
                ]
            }
            self.wfile.write(json.dumps(resp).encode("utf-8"))

        elif path == "/api/v1/config":
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            # Return full config (exercising client-side filtering)
            self.wfile.write(json.dumps({"config": self.config_store}).encode("utf-8"))

        elif path == "/api/v1/slice/status":
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            resp = {
                "state": "done",
                "percent": 100,
                "stats": {
                    "estimated_time_seconds": 3600.0,
                    "filament_used_g": 24.5,
                },
                "warnings": [],
            }
            self.wfile.write(json.dumps(resp).encode("utf-8"))

        elif path == "/api/v1/gcode":
            self.send_response(200)
            self.send_header("Content-Type", "application/octet-stream")
            self.end_headers()
            self.wfile.write(b"; G-CODE GENERATED BY MOCK\nG28\nG1 Z10\n")

        else:
            self.send_response(404)
            self.end_headers()

    def do_POST(self):
        if not self._check_auth():
            return

        if self.path == "/api/v1/slice":
            MockOrcaHandler.slice_attempts += 1
            if MockOrcaHandler.fail_slice_once:
                MockOrcaHandler.fail_slice_once = False
                self.send_response(422)
                self.send_header("Content-Type", "application/json")
                self.end_headers()
                self.wfile.write(json.dumps({"error": "slice_not_started"}).encode("utf-8"))
                return

            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            self.wfile.write(json.dumps({"status": "started"}).encode("utf-8"))

        elif self.path == "/api/v1/slice/cancel":
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            self.wfile.write(json.dumps({"status": "cancelled"}).encode("utf-8"))
        else:
            self.send_response(404)
            self.end_headers()

    def do_PUT(self):
        if not self._check_auth():
            return

        if self.path == "/api/v1/config":
            content_len = int(self.headers.get("Content-Length", 0))
            body = json.loads(self.rfile.read(content_len).decode("utf-8"))
            applied = []
            for k, v in body.items():
                self.config_store[k] = str(v)
                applied.append(k)
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            self.wfile.write(json.dumps({"applied": applied, "errors": {}}).encode("utf-8"))
        else:
            self.send_response(404)
            self.end_headers()


class TestOrcaClient(unittest.TestCase):
    server: http.server.HTTPServer
    server_thread: threading.Thread
    port: int

    @classmethod
    def setUpClass(cls):
        cls.server = http.server.HTTPServer(("127.0.0.1", 0), MockOrcaHandler)
        cls.port = cls.server.server_port
        cls.server_thread = threading.Thread(target=cls.server.serve_forever, daemon=True)
        cls.server_thread.start()

    @classmethod
    def tearDownClass(cls):
        cls.server.shutdown()
        cls.server.server_close()

    def setUp(self):
        self.client = OrcaClient(
            base_url=f"http://127.0.0.1:{self.port}",
            token=MOCK_TOKEN,
            timeout=5.0,
        )
        MockOrcaHandler.slice_attempts = 0
        MockOrcaHandler.fail_slice_once = False

    def test_auth_failure(self):
        bad_client = OrcaClient(
            base_url=f"http://127.0.0.1:{self.port}",
            token="wrong-token",
            timeout=5.0,
        )
        with self.assertRaises(OrcaAuthError):
            bad_client.get_status()

    def test_get_status(self):
        st = self.client.get_status()
        self.assertEqual(st["app"], "OrcaSlicer")
        self.assertEqual(st["presets"]["printer"], "Bambu Lab P1S 0.4 nozzle")

    def test_get_objects(self):
        objs = self.client.get_objects()
        self.assertEqual(len(objs), 2)
        self.assertEqual(objs[0]["name"], "Benchy.stl")

    def test_get_config_and_client_filtering(self):
        # Client filters without query param
        full = self.client.get_config()
        self.assertIn("layer_height", full)
        self.assertIn("filament_cost", full)

        subset = self.client.get_config(keys=["layer_height"])
        self.assertEqual(subset, {"layer_height": "0.2"})

    def test_put_config(self):
        res = self.client.put_config({"layer_height": "0.16", "wall_loops": "3"})
        self.assertEqual(set(res["applied"]), {"layer_height", "wall_loops"})
        # Verify readback
        cfg = self.client.get_config(keys=["layer_height", "wall_loops"])
        self.assertEqual(cfg, {"layer_height": "0.16", "wall_loops": "3"})

    def test_slice_and_status(self):
        res = self.client.slice()
        self.assertEqual(res["status"], "started")

        st = self.client.slice_status()
        self.assertEqual(st["state"], "done")
        self.assertEqual(st["stats"]["estimated_time_seconds"], 3600.0)

    def test_slice_retry_on_slice_not_started(self):
        MockOrcaHandler.fail_slice_once = True
        res = self.client.slice(retry_on_not_started=True)
        self.assertEqual(res["status"], "started")
        self.assertEqual(MockOrcaHandler.slice_attempts, 2)

    def test_get_gcode(self):
        gcode = self.client.get_gcode()
        self.assertIsInstance(gcode, bytes)
        self.assertIn(b"G28", gcode)


if __name__ == "__main__":
    unittest.main()
